A/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('products/' , include('products.urls' , namespace='products')),
    path('orders/' , include('orders.urls' , namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('' , views.HomeView.as_view() , name = 'home'),
    path('bucket/' , views.BucketHome.as_view() , name = 'bucket'),
]

orders/urls.py
from django.urls import path
from . import views


app_name= 'orders'
urlpatterns = [
    path('create/' , views.OrderCreateView.as_view() , name = 'orders_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view() , name = 'order_detail'),
    path('cart/' , views.CartView.as_view() , name='orders_cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() , name = 'cart_add'),
    path('cart/remove/<int:product_id>/' , views.CartRemoveView.as_view() , name='cart_remove' ),
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        return sum(
            item.get_cost()
            for item in self.items.all()
        )


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity =forms.IntegerField(min_value=1 , max_value=5)

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from products.models import Product
from .forms import CartAddForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order, OrderItem


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:orders_cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:orders_cart')


class OrderDetailView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'orders/order.html', {'order': order})


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        return redirect('orders:order_detail', order.id)

orders/templates/orders/cart.html
{% extends 'base.html' %}

<title>{% block title %} Cart {% endblock %}</title>

{% block content %}
<div class="container px-3 my-5 clearfix">
    <!-- Shopping cart table -->
    <div class="card">
        <div class="card-header">
            <h2>Shopping Cart</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">Product Name</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Price</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">Quantity</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                  </tr>
                </thead>

                <tbody>
                {% for item in cart %}
                  <tr>
                    <td class="p-4">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <h6 class="d-block text-dark text-center">{{ item.product }}</h6>
                        </div>
                      </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ item.price }}</td>
                    <td class="align-middle p-4 text-center">{{ item.quantity }}</td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ item.total_price }}</td>
                    <td class="text-center align-middle px-0"><a href="{% url 'orders:cart_remove' item.product.id %}" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- / Shopping cart table -->
            <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
              <div class="mt-4">
                <label class="text-muted font-weight-normal">Promocode</label>
                <input type="text" placeholder="ABC" class="form-control">
              </div>
              <div class="d-flex">
                <div class="text-center mt-4 mr-5">
                  <label class="text-muted font-weight-normal m-1"> Discount: </label>
                  <div class="text-large">0</div>
                </div>
                <div class="text-center mt-4">
                  <label class="text-muted font-weight-normal m-1"> Total price: </label>
                  <div class="text-large"><strong>{{ cart.get_total_price }}</strong></div>
                </div>
              </div>
            </div>

            <div class="float-right">
                <a href="{% url 'home:home' %}"><button type="button" class="btn btn-lg btn-secondary md-btn-flat mt-2 mr-3">Back to shopping</button></a>
                <a href="{% url 'orders:orders_create' %}" class="btn btn-lg btn-primary mt-2">Checkout</a>
            </div>

          </div>
      </div>
  </div>

{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}


{% block content %}

    <h3>Checkout</h3>
    <p>Total: {{ order.get_total_price }}</p>

{% endblock %}