A/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('products/' , include('products.urls' , namespace='products')),
    path('orders/' , include('orders.urls' , namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name= 'orders'
urlpatterns = [
    path('create/' , views.OrderCreateView.as_view() , name = 'orders_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view() , name = 'order_detail'),
    path('cart/' , views.CartView.as_view() , name='orders_cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() , name = 'cart_add'),
    path('cart/remove/<int:product_id>/' , views.CartRemoveView.as_view() , name='cart_remove' ),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductsView.as_view(), name='v_products'),
    path('category/<slug:category_slug>/' , views.ProductsView.as_view() , name='category'),
    path('<slug:slug>/' , views.ProductDetailView.as_view() , name='product_detail'),
]

products/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('products:category' , args=[self.slug , ])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='c_products')
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField()
    available = models.BooleanField(default=False)
    description = models.TextField()
    price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('products:product_detail' , args=[self.slug , ])

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Product, Category
from orders.forms import CartAddForm


class ProductsView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available = True)
        categories = Category.objects.all()
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'products/products.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, 'products/products_detail.html', {'product': product , 'form':form})

products/templates/products/products.html
{% extends 'base.html' %}

<title>{% block title %} All Products {% endblock %}</title>

{% block content %}
    <!-- Section-->
        <h2 class="d-inline"> Category :</h2>
        {% for category in categories %}


            <a href="{{ category.get_absolute_url }}" class="btn btn-outline-secondary">{{ category.name }}</a>

        {% endfor %}
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-3">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product price-->
                                    Price :{{ product.price }} toman
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolute_url }}">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
{% endblock %}

products/templates/products/products_detail.html
{% extends 'base.html' %}
{% load static %}

<title>{% block title %}  Product Detail {% endblock %}</title>
    <head>
        <link href="css/styles.css" rel="stylesheet" />
    </head>
{% block content %}
        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="..." /></div>
                    <div class="col-md-6">
                        <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                        <div class="fs-5 mb-5">
                            <span >Price : {{ product.price }} toman</span>
                        </div>
                        <p class="lead">{{ product.description }}</p>
                        <div class="d-flex">
                            <form action="{% url 'orders:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                {{ form }} <br>
                                <input class="btn btn-outline-dark" type="submit" value="Add to Cart">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Related items section-->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <h2 class="fw-bolder mb-4">Related products</h2>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fancy Product</h5>
                                    <!-- Product price-->
                                    $40.00 - $80.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

{% endblock %}