A/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('products/' , include('products.urls' , namespace='products')),
    path('orders/' , include('orders.urls' , namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name='user_register'),
    path('verify/', views.UserVerifyCodeView.as_view() , name='verify_code'),
    path('login/' , views.UserLoginView.as_view() , name= 'user_login'),
    path('logout/' , views.UserLogoutView.as_view() , name = 'user_logout'),
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('' , views.HomeView.as_view() , name = 'home'),
    path('bucket/' , views.BucketHome.as_view() , name = 'bucket'),
]

orders/urls.py
from django.urls import path
from . import views


app_name= 'orders'
urlpatterns = [
    path('create/' , views.OrderCreateView.as_view() , name = 'orders_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view() , name = 'order_detail'),
    path('cart/' , views.CartView.as_view() , name='orders_cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() , name = 'cart_add'),
    path('cart/remove/<int:product_id>/' , views.CartRemoveView.as_view() , name='cart_remove' ),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductsView.as_view(), name='v_products'),
    path('category/<slug:category_slug>/' , views.ProductsView.as_view() , name='category'),
    path('<slug:slug>/' , views.ProductDetailView.as_view() , name='product_detail'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:home' %}">Tima Fashion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:bucket' %}">Bucket</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'products:v_products' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    {% if request.user.is_authenticated %}
                    <div class="d-flex p-1">
                        <a href="{% url 'accounts:user_logout' %}">
                            <button class="btn btn-outline-dark" type="submit">
                                 <i class="bi bi-person-fill me-1"></i>
                                 Logout
                            </button>
                        </a>
                    </div>
                    {% else %}
                    <div class="d-flex p-1">
                        <a href="{% url 'accounts:user_register' %}">
                            <button class="btn btn-outline-dark" type="submit">
                                 <i class="bi bi-person-fill me-1"></i>
                                 Register
                            </button>
                        </a>
                    </div>
                    <div class="d-flex p-1">
                        <a href="{% url 'accounts:user_login' %}">
                            <button class="btn btn-outline-dark" type="submit">
                                 <i class="bi bi-person-fill me-1"></i>
                                 Login
                            </button>
                        </a>
                    </div>
                    {% endif %}
                    <div class="d-flex p-1">
                            <a href="{% url 'orders:orders_cart' %}">
                                <button class="btn btn-outline-dark" type="submit">
                                    <i class="bi-cart-fill me-1"></i>
                                    Cart
                                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart | length }}</span>
                                </button>
                            </a>
                    </div>
                </div>
            </div>
        </nav>